
version: '3.8'

services:
  host:
    build:
      context: ./host
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    networks:
      - mfe-network

  mfe-design-system:
    build:
      context: ./mfe-design-system
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    networks:
      - mfe-network

  mfe-store:
    build:
      context: ./mfe-store
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
    networks:
      - mfe-network

networks:
  mfe-network:
    driver: bridge
